# Generated by Django 3.1.4 on 2021-11-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('descricao', models.TextField(max_length=255, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/')),
                ('setor', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('usuabr', models.CharField(max_length=100, null=True)),
                ('usures', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
