# Generated by Django 3.1.4 on 2021-12-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='datger',
            field=models.DateField(null=True),
        ),
    ]
