# Generated by Django 3.1.4 on 2021-12-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado_datger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='datger',
            field=models.DateTimeField(null=True),
        ),
    ]
