# Generated by Django 3.1.4 on 2021-12-17 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_auto_20211217_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='datger',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 15, 11, 2, 757709)),
        ),
    ]
