# Generated by Django 3.1.4 on 2021-12-17 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_auto_20211217_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='datger',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 18, 15, 16, 34, 579028), null=True),
        ),
    ]
