# Generated by Django 3.1.4 on 2021-12-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_auto_20211217_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='datger',
        ),
    ]
